
.include "_crystalis_defines_constants.asm"
.include "_crystalis_defines_memory.asm"

.segment "HEADER"

.byte $4E, $45, $53, $1A, $10, $10, $42, $00
.byte $00, $00, $00, $00, $00, $00, $00, $00

.include "crystalis_prg_0x0.asm"
.include "crystalis_prg_0x1.asm"
.include "crystalis_prg_0x2.asm"
.include "crystalis_prg_0x3.asm"
.include "crystalis_prg_0x4.asm"
.include "crystalis_prg_0x5.asm"
.include "crystalis_prg_0x6.asm"
.include "crystalis_prg_0x7.asm"
.include "crystalis_prg_0x8.asm"
.include "crystalis_prg_0x9.asm"
.include "crystalis_prg_0xA.asm"
.include "crystalis_prg_0xB.asm"
.include "crystalis_prg_0xC.asm"
.include "crystalis_prg_0xD.asm"
.include "crystalis_prg_0xE.asm"
.include "crystalis_prg_0xF.asm"

.include "crystalis_chr_0x0.asm"
.include "crystalis_chr_0x1.asm"
.include "crystalis_chr_0x2.asm"
.include "crystalis_chr_0x3.asm"
.include "crystalis_chr_0x4.asm"
.include "crystalis_chr_0x5.asm"
.include "crystalis_chr_0x6.asm"
.include "crystalis_chr_0x7.asm"
.include "crystalis_chr_0x8.asm"
.include "crystalis_chr_0x9.asm"
.include "crystalis_chr_0xA.asm"
.include "crystalis_chr_0xB.asm"
.include "crystalis_chr_0xC.asm"
.include "crystalis_chr_0xD.asm"
.include "crystalis_chr_0xE.asm"
.include "crystalis_chr_0xF.asm"